spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://irsntedegjojko:224604b35472d750625cd516ef46415a5a74bb8e8bc940938e7a560f171745cb@ec2-50-16-196-238.compute-1.amazonaws.com:5432/dcn6gfsvo80dtq
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
    